### ISSUE TITLE
美团运行报错，能看下吗？

### ISSUE THREAD

**Issue by blusunny** [arvinsblog/deepsea#4]
## 开始执行... 2024-10-21 21:56:11

/ql/data/scripts/blusunny_qinglong/meituanV4.js:1
# -*- coding:utf-8 -*-
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.1

## 执行结束... 2024-10-21 21:56:12  耗时 1 秒

**Comment by arvinsblog** [comment]
> ## 开始执行... 2024-10-21 21:56:11
> /ql/data/scripts/blusunny_qinglong/meituanV4.js:1
> 
> # -_- coding:utf-8 -_-
> ^
> 
> SyntaxError: Invalid or unexpected token at internalCompileFunction (node:internal/vm:77:18) at wrapSafe (node:internal/modules/cjs/loader:1288:20) at Module._compile (node:internal/modules/cjs/loader:1340:27) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) at node:internal/main/run_main_module:28:49
> 
> Node.js v20.11.1
> 
> ## 执行结束... 2024-10-21 21:56:12 耗时 1 秒

自己反思一下变量有没有填错什么的，

**Comment by blusunny** [comment]
好的，已反思，已解决，谢谢大佬

**Comment by blusunny** [comment]
> 好的，已反思，已解决，谢谢大佬



> > ## 开始执行... 2024-10-21 21:56:11
> > /ql/data/scripts/blusunny_qinglong/meituanV4.js:1
> > # -_- coding:utf-8 -_-
> > ^
> > SyntaxError: Invalid or unexpected token at internalCompileFunction (node:internal/vm:77:18) at wrapSafe (node:internal/modules/cjs/loader:1288:20) at Module._compile (node:internal/modules/cjs/loader:1340:27) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) at node:internal/main/run_main_module:28:49
> > Node.js v20.11.1
> > ## 执行结束... 2024-10-21 21:56:12 耗时 1 秒
> 
> 自己反思一下变量有没有填错什么的，

好的，已反思，已解决，谢谢大佬
